#!/bin/bash

read -p "ENTER STARTING YEAR: " start
read -p "ENTER ENDING YEAR: " end

count=0

if (( start > end )); then
temp=$start
start=$end
end=$temp
fi

for (( y=start; y<=end; y++ )); do
if (( (y%400==0) || (y%4==0 && y%100!=0) )); then
echo "$y"
((count++))
fi
done

echo "Total leap years: $count"

